### ISSUE TITLE
Investigate setup.py behavior

### ISSUE THREAD

**Issue by williamshen-nz** [Learning-and-Intelligent-Systems/lisdf#25]
I was trying to `pip install lisdf@git+https://github.com/Learning-and-Intelligent-Systems/lisdf.git`

It was super slow, and it seemed like it was maybe trying to pull the lisdf-models sub-module. 

Here's the folder size as it was downloading and setting up. For comparison, the .git folder was only 7.4MB on a fresh clone from main and the lisdf-models directory should be empty if we are not pulling the submodule. 

```
  Running command git submodule update --init --recursive -q

  Preparing metadata (setup.py) ... done
...
❯ du -hd1
112K	./tests
 20K	./scripts
4.0K	./.github
 74M	./lisdf-models
305M	./.git
396K	./lisdf
380M	.
```

Could be remnants of an old .git where we had all the models here?

**Comment by tomsilver** [comment]
yeah I think that it is installing the submodule. relevant: https://github.com/pypa/pip/issues/6374

**Comment by tomsilver** [comment]
the only workarounds I can think of:
1. make lisdf-models an optional dependency (like lint, mypy, etc.), rather than a submodule
2. list lisdf on pypi and actually do `pip install lisdf`

I don't know of many downsides to (1) except that it would require a little work. Downside of (2) is that we would have to regularly release versions on pypi whenever there are important updates to the git repo.

**Comment by williamshen-nz** [comment]
I think (1) is probably a better option for now since the codebase isn't super release ready.

How would we have it as an optional dependency? Right now it's not a python package just a collection of files

**Comment by tomsilver** [comment]
right, so we would have to add a setup.py to lisdf-models, which is hopefully easy enough (I can take a look at that now)

**Comment by williamshen-nz** [comment]
We could also extract the models used in the tests into the test directory. That way, we can remove the dependency entirely and only people who want to use the models will clone it.
